# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ecf680090f7ec6e77f9bbef705c74d888665491b81bb6a709d79b2e425c7867d9a67592e47e514c0025bbbcc7cb0d38725692758237be4fb4b60b8ac8883498

test:
  secret_key_base: 629634993e859569a565e6311ec124d7d13926815c4ab353020e56ea6854401e29c0cad5eae11f7ebf92795069e296fb3543a38f9556de8b6dcb8efc3ae708b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
